export const images = [
    { src: './images/apple.png', matched: false },
    { src: './images/badge.png', matched: false },
    { src: './images/chick.png', matched: false },
    { src: './images/chess.png', matched: false },
    { src: './images/coffee-full.png', matched: false },
    { src: './images/body-building.png', matched: false },
    { src: './images/coffee.png', matched: false },
    { src: './images/database.png', matched: false },
    { src: './images/eye.png', matched: false },
    { src: './images/game.png', matched: false },
    { src: './images/glasses.png', matched: false },
    { src: './images/goal.png', matched: false },
    { src: './images/landline.png', matched: false },
    { src: './images/sheep.png', matched: false },
    { src: './images/swords.png', matched: false },
    { src: './images/target.png', matched: false },
    { src: './images/teamwork.png', matched: false },
    { src: './images/yoyo.png', matched: false },
];
